### ISSUE TITLE
Describe Product Group level in POM

### ISSUE THREAD

**Issue by andreas-rafaelsen** [digdir/baksia#629]

**Comment by MrCarrera** [comment]
@andreas-rafaelsen can you describe this issue?

**Comment by MrCarrera** [comment]
Is this consider as "done" since the text is added @andreas-rafaelsen @altinnadmin ?: 
"Produktgrupper
Digdir lager fellesløsninger som er til gode for samfunnet. Fellesløsninger er små byggeklosser som kan brukes av kundene etter individuelle behov. For å sikre at videreutvikling ikke blir fragmentert, er løsningene inndelt i produktgrupper, som beslutter den overordna strategiske retningen i en produktgruppestrategi.

Produktgruppene inneholder produkter fra begge leverandøravdelingene, og blir fagmessig ledet av en produktgruppe-leder."

**Comment by altinnadmin** [comment]
> Is this consider as "done" 

Yes, just add a link in the pom and call it a day :) 
![image](https://github.com/user-attachments/assets/28919af3-02e0-4b12-b154-2ea36720a7f4)
